pipeline {
    agent any
 
    tools {
        maven 'Maven3'
        jdk  'jdk21'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'New_Branch_1', url: 'https://github.com/surajforu/Selenium_Automation_project'
            }
        }
 
        stage('Build') {
            steps {
                dir('TutorialsNinjaFramework') {
                    bat 'mvn clean'
                }
            }
        }
 
        stage('Compile') {
            steps {
                dir('TutorialsNinjaFramework') {
                    bat 'mvn compile'
                }
            }
        }
 
        stage('Test') {
            steps {
                dir('TutorialsNinjaFramework') {
                    bat 'mvn test'
                }
            }
        }
 
        stage('Package') {
            steps {
                dir('TutorialsNinjaFramework') {
                    bat 'mvn package'
                }
            }
        }
    }
    stage('Docker Build') {

    steps {

        bat 'docker build -t cucumber-framework .'

    }

}

 

stage('Docker Run') {

    steps {

        bat 'docker run --rm cucumber-framework'

    }

}
stage('Build Docker Image') {
            steps {
                bat 'docker build -t cucumber-project .'
            }
        }
        stage('Run Tests Inside Container') {
            steps {
                bat 'docker run --rm cucumber-project'
            }
        }
    }
    post {
        always {
            junit '*/target/surefire-reports/.xml'
        }
    }
    
 
    post {
        success {
            echo 'Build Successful'
        }
 
        failure {
            echo 'Build Failed'
        }
    }
}
