pipeline {
agent any


tools {
    maven 'Maven3'
    jdk 'jdk21'
}

stages {

    stage('Checkout') {
        steps {
            git branch: 'New_Branch_1',
                url: 'https://github.com/surajforu/Selenium_Automation_project.git'
        }
    }

    stage('Build') {
        steps {
            dir('TutorialsNinjaFramework') {
                bat 'mvn clean'
            }
        }
    }

    stage('Compile') {
        steps {
            dir('TutorialsNinjaFramework') {
                bat 'mvn compile'
            }
        }
    }

    stage('Test') {
        steps {
            dir('TutorialsNinjaFramework') {
                bat 'mvn test'
            }
        }
    }

    stage('Package') {
        steps {
            dir('TutorialsNinjaFramework') {
                bat 'mvn package'
            }
        }
    }

    stage('Docker Build') {
        steps {
            dir('TutorialsNinjaFramework') {
                bat 'docker build -t cucumber-framework .'
            }
        }
    }

    stage('Docker Run') {
        steps {
            bat 'docker run --rm cucumber-framework'
        }
    }
}

post {
    always {
        junit 'TutorialsNinjaFramework/target/surefire-reports/*.xml'
    }

    success {
        echo 'Build Successful'
    }

    failure {
        echo 'Build Failed'
    }
}


}
